# Generated by Django 5.1.6 on 2025-03-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='attbute_type',
            new_name='attribute_type',
        ),
    ]
