# Generated by Django 5.1.6 on 2025-02-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="url",
        ),
    ]
